### PR TITLE
more https and print()

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by haraldschilly** [comment]
Hmm, why are there suddenly brackets for the print statement for Sage? This should always work without them to be compatible with old material.

**Comment by fchapoton** [comment]
well, print with a bracket works in both py2 and py3. Adding them here helps to prepare people for py3

**Comment by haraldschilly** [comment]
I don't understand. Why has updating Sage to use Python 3 an impact on the print statement? IMHO it shouldn't. It would be very bad if that's the case!

**Comment by fchapoton** [comment]
You may not like it, but it will happen. It makes no sense to allow people
to use python3 if they do not switch to the python3 syntax. But here is not
the place to discuss that. See for example
https://trac.sagemath.org/ticket/23674

Le dim. 10 mars 2019 à 14:09, Harald Schilly <notifications@github.com> a
écrit :

**Pull request merged**
